import { Link } from 'react-router-dom';
import PropTypes from 'prop-types';
import { ArrowDownLeft, ArrowUpRight, Bell, ChevronRight, CirclePlus, CreditCard, MoreHorizontal, Send, WalletCards } from 'lucide-react';

const activities = [
  { initials: 'AM', color: 'bg-amber-100 text-amber-700', name: 'Amina Mwangi', detail: 'Sent to M-Pesa • Today, 10:42', amount: '− $260.00', status: 'Completed' },
  { initials: 'JM', color: 'bg-violet-100 text-violet-700', name: 'James Miller', detail: 'Received from United Kingdom • Yesterday', amount: '+ $485.50', status: 'Completed' },
  { initials: 'CR', color: 'bg-sky-100 text-sky-700', name: 'Carlos Ruiz', detail: 'Sent to bank account • Sep 12', amount: '− $120.00', status: 'In progress' },
];

const Dashboard = () => <div className="min-h-[720px] bg-[#f7f9fc] py-8 lg:py-12"><div className="mx-auto max-w-7xl px-5 lg:px-8">
  <div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-center"><div><p className="text-sm text-slate-500">Thursday, September 17</p><h1 className="mt-1 text-3xl font-bold tracking-[-.05em] text-slate-950">Good morning, David</h1></div><div className="flex gap-3"><button className="grid h-10 w-10 place-items-center rounded-xl border border-slate-200 bg-white text-slate-600"><Bell size={18} /></button><Link to="/send" className="inline-flex items-center gap-2 rounded-xl bg-[#0f766e] px-4 py-2.5 text-sm font-semibold text-white hover:bg-[#0b645e]"><Send size={16} /> Send money</Link></div></div>
  <div className="mt-8 grid gap-5 lg:grid-cols-[1.35fr_.65fr]"><section className="rounded-3xl bg-[#102522] p-6 text-white sm:p-8"><div className="flex items-start justify-between"><div><p className="text-sm text-[#b6d8ce]">Total balance</p><h2 className="mt-2 text-4xl font-bold tracking-[-.055em]">$2,840.50</h2><p className="mt-2 text-sm text-[#8ee3c7]">+$405.20 <span className="text-[#b6d8ce]">this month</span></p></div><span className="grid h-11 w-11 place-items-center rounded-xl bg-white/10 text-[#8ee3c7]"><WalletCards size={21} /></span></div><div className="mt-10 flex flex-wrap gap-3"><Link to="/send" className="inline-flex items-center gap-2 rounded-xl bg-white px-4 py-2.5 text-sm font-semibold text-[#102522]"><ArrowUpRight size={16} /> Send</Link><Link to="/receive" className="inline-flex items-center gap-2 rounded-xl bg-white/10 px-4 py-2.5 text-sm font-semibold text-white hover:bg-white/15"><ArrowDownLeft size={16} /> Receive</Link></div></section>
  <section className="rounded-3xl border border-slate-200 bg-white p-6 sm:p-7"><div className="flex items-center justify-between"><div><p className="text-sm text-slate-500">Available rewards</p><p className="mt-1 text-3xl font-bold tracking-[-.04em]">$18.40</p></div><span className="grid h-11 w-11 place-items-center rounded-xl bg-[#fff4d7] text-[#b67800]"><CreditCard size={20} /></span></div><p className="mt-5 text-sm leading-6 text-slate-500">Invite a friend and earn $10 when they send their first transfer.</p><button className="mt-4 text-sm font-bold text-[#087869]">Invite friends →</button></section></div>
  <div className="mt-8 grid gap-7 lg:grid-cols-[1.35fr_.65fr]"><section className="rounded-3xl border border-slate-200 bg-white"><div className="flex items-center justify-between border-b border-slate-100 px-6 py-5"><div><h2 className="font-bold tracking-[-.02em] text-slate-900">Recent activity</h2><p className="mt-0.5 text-sm text-slate-500">Your latest transfers</p></div><Link to="/history" className="text-sm font-semibold text-[#087869]">View all</Link></div><div className="divide-y divide-slate-100">{activities.map((item) => <div key={item.name} className="flex items-center gap-3 px-5 py-4 sm:px-6"><span className={`grid h-10 w-10 shrink-0 place-items-center rounded-full text-xs font-bold ${item.color}`}>{item.initials}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold text-slate-800">{item.name}</p><p className="mt-0.5 truncate text-xs text-slate-500">{item.detail}</p></div><div className="text-right"><p className={`text-sm font-bold ${item.amount.startsWith('+') ? 'text-[#087869]' : 'text-slate-800'}`}>{item.amount}</p><p className={`mt-0.5 text-xs ${item.status === 'Completed' ? 'text-[#087869]' : 'text-amber-600'}`}>{item.status}</p></div></div>)}</div></section>
  <aside className="rounded-3xl border border-slate-200 bg-white p-6"><div className="flex items-center justify-between"><h2 className="font-bold tracking-[-.02em]">Your recipients</h2><button className="text-slate-400"><MoreHorizontal size={19} /></button></div><p className="mt-1 text-sm text-slate-500">Send again in just a few taps.</p><div className="mt-5 space-y-3"><Recipient initials="AM" name="Amina Mwangi" detail="Kenya" color="bg-amber-100 text-amber-700" /><Recipient initials="JM" name="James Miller" detail="United Kingdom" color="bg-violet-100 text-violet-700" /><Recipient initials="CR" name="Carlos Ruiz" detail="Mexico" color="bg-sky-100 text-sky-700" /></div><Link to="/profile" className="mt-5 flex items-center justify-center gap-1 rounded-xl bg-slate-50 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-100">Manage recipients <ChevronRight size={16} /></Link></aside></div>
</div></div>;

const Recipient = ({ initials, name, detail, color }) => <div className="flex items-center gap-3"><span className={`grid h-9 w-9 place-items-center rounded-full text-xs font-bold ${color}`}>{initials}</span><div className="flex-1"><p className="text-sm font-semibold text-slate-800">{name}</p><p className="text-xs text-slate-500">{detail}</p></div><button className="grid h-8 w-8 place-items-center rounded-lg text-[#087869] hover:bg-[#eafaf4]" aria-label={`Send money to ${name}`}><CirclePlus size={18} /></button></div>;

Recipient.propTypes = {
  initials: PropTypes.string.isRequired,
  name: PropTypes.string.isRequired,
  detail: PropTypes.string.isRequired,
  color: PropTypes.string.isRequired,
};

export default Dashboard;
