import { useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, CheckCircle2, Mail, ShieldCheck } from 'lucide-react';

const Verify = () => { const [code, setCode] = useState(['', '', '', '', '', '']); const [complete, setComplete] = useState(false); const change = (value, index) => { if (!/^[0-9]?$/.test(value)) return; const next = [...code]; next[index] = value; setCode(next); if (value && index < 5) document.getElementById(`verify-${index + 1}`)?.focus(); };
  return <div className="flex min-h-[calc(100vh-76px)] items-center justify-center bg-[#f7f9fc] px-5 py-12"><div className="w-full max-w-md rounded-3xl border border-slate-200 bg-white p-7 text-center shadow-sm sm:p-9"><span className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-[#e6faf2] text-[#087869]">{complete ? <CheckCircle2 size={27} /> : <Mail size={25} />}</span>{complete ? <><h1 className="mt-6 text-2xl font-bold tracking-[-.04em] text-slate-900">You’re all verified</h1><p className="mt-3 leading-6 text-slate-600">Your account is ready. You can now send and receive money with SwiftSend.</p><Link to="/dashboard" className="mt-7 inline-flex items-center gap-2 rounded-xl bg-[#0f766e] px-5 py-3 text-sm font-semibold text-white">Go to dashboard <ArrowRight size={17} /></Link></> : <><h1 className="mt-6 text-2xl font-bold tracking-[-.04em] text-slate-900">Check your email</h1><p className="mt-3 leading-6 text-slate-600">We sent a 6-digit verification code to <strong className="font-semibold text-slate-800">david@example.com</strong>.</p><div className="mt-7 flex justify-center gap-2">{code.map((digit, index) => <input key={index} id={`verify-${index}`} value={digit} onChange={(e) => change(e.target.value, index)} onKeyDown={(e) => { if (e.key === 'Backspace' && !digit && index > 0) document.getElementById(`verify-${index - 1}`)?.focus(); }} maxLength="1" inputMode="numeric" className="h-12 w-10 rounded-lg border border-slate-200 text-center text-lg font-bold outline-none focus:border-[#39b697] focus:ring-4 focus:ring-[#e1f7ef] sm:w-11" />)}</div><button onClick={() => setComplete(code.every(Boolean))} disabled={!code.every(Boolean)} className="mt-7 flex w-full items-center justify-center gap-2 rounded-xl bg-[#0f766e] py-3 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:opacity-45">Verify email <ArrowRight size={17} /></button><button className="mt-5 text-sm font-semibold text-[#087869]">Resend code</button><p className="mt-7 flex items-center justify-center gap-1.5 text-xs text-slate-400"><ShieldCheck size={15} /> Your information is always protected.</p></>}</div></div>;
};

export default Verify;
